ktor:
    application:
        modules:
            - J.dev.ApplicationKt.module
            - J.dev.Individuals.IndividualRoutesKt.IndividualRoutes
    deployment:
      port: 8080
      host: localhost